config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'users/index'
  get 'users/show'

  devise_for :users, :controllers => { registrations: 'registrations' }
  match('users/:id/add_profile_image' , {:via => :post, :to => 'users#add_profile_image'})
  match('users/:id/new_post' , {:via => :post, :to => 'users#new_post'})
  match('users/:id/follow' , {:via => :get, :to => 'users#follow'})
  match('users/:id/unfollow' , {:via => :get, :to => 'users#unfollow'})
  match('users/:id/view_followers' , {:via => :get, :to => 'users#view_followers'})
  match('users/:id' , {:via => :get, :to => 'users#show'})

  root 'home#index'
  get 'home/index'

end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :pictures

  #socilization
  acts_as_followable
  acts_as_follower

  #paperclip
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment :image,
    content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
    size: { in: 0..10.megabytes }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  def after_update_path_for(resource)
    users_show_path(:id => current_user.id)
  end

  def after_sign_in_path_for(resource_or_scope)
    users_show_path(:id => current_user.id)
  end

  def after_sign_up_path_for(resource)
    users_show_path(:id => current_user.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :content)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def after_update_path_for(resource)
    users_show_path(:id => current_user.id)
  end

  def after_sign_in_path_for(resource_or_scope)
    users_show_path(:id => current_user.id)
  end

  def after_sign_up_path_for(resource)
    users_show_path(:id => current_user.id)
  end

private
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order("updated_at DESC")
    @changed = {:user => {:userid => @user.id, :first => @user.first_name, :last => @user.last_name}}

    respond_to do |format|
      format.html { render 'show.html.erb', status: 200 }
      format.json { render json: @changed, status: 200 }
      # format.json { render :json => @user.to_json(
      #   :only => [:id, :first_name, :last_name]), status: 200 }
    end

  end

  def new_post
    @user = current_user
    @post = Post.new(:content => params[:post_content])
    @post.save
    @user.posts << @post
    @user.save
    @post = Post.where(:user_id => current_user.id)

    redirect_to action: :show
  end

  def follow
    @user = User.find(params[:id])
    current_user.follow!(@user)
    redirect_to action: :show
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.unfollow!(@user)
    redirect_to action: :show
  end

  def view_followers
    @user = User.find(params[:id])
    @following = @user.followees(User)
    @yourFollowers = @user.followers(User)
  end

  def add_profile_image
    @user = current_user
    @user.image = params[:profile_image]
    @user.save
    redirect_to action: :show
  end

private
  def user_params
     params.require(:user).permit(:first_name, :last_name, :posts, :image, posts_attributes: [:id, :content, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_header.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Spacebook</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><a href="#">Right Button Active</a></li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li><a href="#">Left Nav Button</a></li>
    </ul>
  </section>
</nav>

app/views/home/index.html.erb
<h1 class="text-center">Welcome to Spacebook</h1>
<h4 class="text-center">A page that started as a Facebook clone until I realized it's more of a Twitter Clone</h4>
<br>
<h4 class="text-center">Log in to start wasting time</h4>

<div class="row">
  <div class="small-3 columns"><img src="http://timemanagementninja.com/wp-content/uploads/2013/02/Wasting-Time.jpg"></a></div>
  <div class="small-3 columns"><img src="http://timemanagementninja.com/wp-content/uploads/2013/02/Wasting-Time.jpg"></a></div>
  <div class="small-3 columns"><img src="http://timemanagementninja.com/wp-content/uploads/2013/02/Wasting-Time.jpg"></a></div>
  <div class="small-3 columns"><img src="http://timemanagementninja.com/wp-content/uploads/2013/02/Wasting-Time.jpg"></a></div>
</div>

<!-- <div class="row">
  <div class="small-5">
    <div class="panel">
      <h5>A fancy panel entry</h5>
      <p>Maecenas blandit gravida urna, eu tincidunt turpis scelerisque id. Sed eleifend, nunc quis rhoncus accumsan, ante purus bibendum metus.</p>
    </div>
  </div>
</div> -->

app/views/layouts/_headerlog.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Spacebook</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <% if user_signed_in? %>
        <li><a href="/users/<%= current_user.id %>"><strong><%= current_user.first_name %></a></li>

        <li><%= link_to 'See Users', users_index_path %></li>
        <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
       <% else %>
         <li><%= link_to "Sign up", new_user_registration_path %></li>
         <li><%= link_to "Login", new_user_session_path %></li>
       <% end %>
    </div>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Spacebook" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <!--navbar start-->
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a href="#">Spacebook</a></h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <% if user_signed_in? %>
            <li><a href="/users/<%= current_user.id %>"><strong><%= current_user.first_name %></a></li>
            <li><%= link_to 'See Users', users_index_path %></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
           <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
           <% end %>
        </ul>
        <!-- Left Nav Section -->
        <ul class="left">
        </ul>
      </section>
    </nav>
    <!--end navbar-->

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user_id %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_image_modal.html.erb
<div id="myModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  <h2 id="modalTitle" class="text-center">Add/Change Your Profile Picture</h2>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
  <hr>
  <div class="row">
    <div class="small-8 small-centered columns">
      <div class="small-4 columns">
        <div class="current-pic text-center">
          <% if !@user.image.blank? %>
            <%= image_tag @user.image.url(:large), class: "user_pic" %>
          <% else %>
            <img src="/system/user_default.png" class="user_pic"/>
          <% end %>
        </div>
      </div>

      <div class="small-8 columns">
        <div class="pic-form">
          <form role="form" class="form-group add_profile_image" id="user_profile_image" action="/users/<%= @user.id %>/add_profile_image" enctype="multipart/form-data" accept-charset="UTF-8" method="post">
            <div id="profile_image" class="muted form-group toHide">
              <label class="muted" for="user_image"><strong>Upload an Image From Your PC:</strong></label>
              <input type="file" class="file" name="profile_image" id="profile_image" />
            </div>
            <div class="form-group actions">
              <input class="button" type="submit" name="commit" value="Add"/>
            </div>
          </form>
        </div><!--end pic-form-->
      </div>
    </div><!--end column-8-->

  </div><!--end row-->
</div>

app/views/users/index.html.erb
<h1 class="text-center">Find People</h1>
<% @users.each do |user| %>
  <p class="text-center"><a href="/users/<%= user.id %>"><%= user.first_name + " " + user.last_name %><a></p>
<% end %>

app/views/users/show.html.erb
<div class="user-head">
  <div class="row">
    <!--user-pic-->
    <div class="small-4 columns">
      <div class="user_pic_area">
        <a href="#" data-reveal-id="myModal" class="no-hover">
        <% if !@user.image.blank? %>
          <%= image_tag @user.image.url(:large), class: "user_pic" %>
        <% else %>
          <img src="/system/user_default.png" class="user_pic"/>
        <% end %>
        </a>
        <%= render 'image_modal' %>
      </div><!--end user-pic-->
    </div>

    <div class="name-and-nav small-8 columns">
      <br>
      <div class="row">
        <div class="small-12 columns">
          <!--user-name-->
          <h1 class="inline"><%= @user.first_name + " " + @user.last_name %></h1>
        <!--follow button business-->
          <% if user_signed_in? %>
            <% if @user != current_user && !current_user.follows?(@user) %>
              <div class="text-center inline"><a href="/users/<%= @user.id %>/follow" class="large button fl-btn">Follow</a></div>
            <% elsif @user != current_user && current_user.follows?(@user) %>
              <div class="text-center inline"><a href="/users/<%= @user.id %>/unfollow" class="large button fl-btn">Unfollow</a></div>
            <% end %>
          <% end %>
        </div>
      </div>
      <br><br><br>

      <div class="row">
        <!--sub nav bar-->
        <nav class="top-bar" data-topbar role="navigation">
          <section class="top-bar-section">
            <!-- Right Nav Section -->
            <!-- <ul class="right">
              <li class="active"><a href="#">Right Button Active</a></li>
              <li class="has-dropdown">
                <a href="#">Right Button Dropdown</a>
                <ul class="dropdown">
                  <li><a href="#">First link in dropdown</a></li>
                  <li class="active"><a href="#">Active link in dropdown</a></li>
                </ul>
              </li>
            </ul> -->

            <!-- Left Nav Section -->
            <ul class="left">
              <li class="no-li-deco"><a href="/users/<%= @user.id %>/view_followers">Followers</a></li>
            </ul>
          </section>
        </nav>
      </div><!--row sub-nav-->
    </div><!--name-and-nav nav-->
  </div><!--row-->
</div><!--user-head end-->
<br>

<!--start body-->
<div class="user-body">
  <div class="row">
    <!--User pictures start-->
    <div class="small-4 columns">
      <div class="pictures-area">

        <div class="pictures-header">
          <p class="margin-auto">Pictures (0)</p> <!--TODO add variable for number of pictures-->
          <hr>
        </div>

        <div class="pictures-body">
        </div>
      </div>
    </div>

    <!--start posts-->
    <div class="posts small-8 columns">
      <!--start make-posts-->
      <% if current_user == @user %>
      <div class="make-post">
        <div class="make-post-top">
          <p><strong>Make a post</strong></p>
        </div>

        <div class="make-post-body">
          <form role="form" class="form-group new-post" id="new-post" action="/users/<%= @user.id %>/new_post" enctype="multipart/form-data" accept-charset="UTF-8" method="post">
          <textarea class="form-control" rows="2" name="post_content" id="post_content"></textarea>
        </div>

        <div class="make-post-submit">
          <input class="button med" type="submit" name="commit" value="Post"/>
        </div>
      </form>

      </div><!--end make-post-->
      <br>
      <% end %>

      <!--start posts-display-->
      <div class="posts-display">
        <% @posts.each do |post| %>
          <div class="single-post">
            <p><%= post.content %></p>
            <hr>
            <p>Posted: <%= time_ago_in_words(post.created_at) %> ago</p>
          </div>
        <% end %>
      </div><!--post-display-->
    </div><!--end posts-->

  </div><!--end row-->
</div><!--end user-body-->

app/views/users/view_followers.html.erb
<br>
<div class="row follow-space">
  <div class="small-6 columns">

      <h3 class="text-center">Currently Following (<%= @following.length %>):</h3>
      <% if @following != [] %>
        <% @following.each do |f| %>

            <div class="user_box inline">
              <div class="pic">
                <a href="/users/<%= f.id %>" class="no-hover">
                  <% if !f.image.blank? %>
                    <%= image_tag f.image.url(:med), class: "user_thumb" %>
                  <% else %>
                    <img src="/system/user_default.png" class="user_thumb"/>
                  <% end %>
                  <p class="text-center"><%= f.first_name %> <%= f.last_name %></p>
                </a>
              </div>
            </div>

        <% end %>

      <% end %>

  </div>

  <div class="small-6 columns">

      <h3 class="text-center">Current Followers (<%= @yourFollowers.length %>):</h3>
      <% if @yourFollowers != [] %>
        <% @yourFollowers.each do |f| %>

            <div class="user_box inline">
              <div class="pic">
                <a href="/users/<%= f.id %>" class="no-hover">
                  <% if !f.image.blank? %>
                    <%= image_tag f.image.url(:med), class: "user_thumb" %>
                  <% else %>
                    <img src="/system/user_default.png" class="user_thumb"/>
                  <% end %>
                  <p class="text-center"><%= f.first_name %> <%= f.last_name %></p>
                </a>
              </div>
            </div>

        <% end %>
      <% end %>

  </div>

</div><!--end follow-space-->